# Generated by Django 5.0.2 on 2024-03-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('H_Name', models.CharField(default='3', max_length=120, verbose_name='hotel name')),
                ('Email', models.CharField(default='3', max_length=120, verbose_name='hotel name')),
                ('Phon_Number', models.CharField(default='3', max_length=120, verbose_name='hotel name')),
                ('H_Locaation', models.CharField(default='3', max_length=120, verbose_name='hotel addres')),
                ('Superior_Room', models.CharField(default='3', max_length=30)),
                ('Deluxe_Room', models.CharField(default='3', max_length=30)),
                ('single_Occupation', models.CharField(default='3', max_length=30)),
                ('Double_Occupation', models.CharField(default='3', max_length=30)),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
