# Generated by Django 5.0.2 on 2024-03-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotels',
            name='level',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='Discreption',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='Payment',
        ),
        migrations.AddField(
            model_name='hotels',
            name='Deluxe_Room',
            field=models.CharField(default='3', max_length=30),
        ),
        migrations.AddField(
            model_name='hotels',
            name='Double_Occupation',
            field=models.CharField(default='3', max_length=30),
        ),
        migrations.AddField(
            model_name='hotels',
            name='Email',
            field=models.CharField(default='3', max_length=120, verbose_name='hotel name'),
        ),
        migrations.AddField(
            model_name='hotels',
            name='Phon_Number',
            field=models.CharField(default='3', max_length=120, verbose_name='hotel name'),
        ),
        migrations.AddField(
            model_name='hotels',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='hotels',
            name='Superior_Room',
            field=models.CharField(default='3', max_length=30),
        ),
        migrations.AddField(
            model_name='hotels',
            name='single_Occupation',
            field=models.CharField(default='3', max_length=30),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='H_Locaation',
            field=models.CharField(default='3', max_length=120, verbose_name='hotel addres'),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='H_Name',
            field=models.CharField(default='3', max_length=120, verbose_name='hotel name'),
        ),
        migrations.DeleteModel(
            name='reat',
        ),
    ]
