# Generated by Django 5.0.2 on 2024-03-03 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0002_remove_hotels_level_remove_hotels_discreption_and_more'),
    ]

    operations = [
    ]
